### ISSUE TITLE
PHPStorm freezes for a few seconds several times

### ISSUE THREAD

**Issue by rubensrocha** [jonathanlermitage/intellij-extra-icons-plugin#114]
* Plugin version: 2022.1.13
* OS: Linux Mint 21
* IDE Version: 2022.2.3  Build #PS-222.4345.15, built on October 5, 2022

IDE freezes for a few seconds several times in a row, either when I click on a part of the code to do some editing, or when I switch between open files, or scroll through the list of files to open a new file for editing.

I've already used the Repair IDE option, and also set Antialiasing to Greyscale, still the same thing. Whenever the freeze happens, in System Monitor the CPU usage graph goes to 100%, then back to normal.

I created an [Issue on YouTrack](https://youtrack.jetbrains.com/issue/WI-69673/IDE-freezes-for-a-few-seconds-several-times) and was recommended to disable the plugin, which in fact resolved the freezing issue.

**Comment by jonathanlermitage** [comment]
@rubensrocha 
It may be a problem with the usage of the IDE filename index.  
The plugin uses the IDE filename index in order to detect some files, but it's a bit broken since 2022 IDEs (we can't simply query the index, this is annoying 😅), and plugin developers have to use some workarounds. It should be reworked next year, but for now I think we can simply disable the usage of these indexes. You will only loose support for Helm, Angular and GraphQL icons provided by Extra icons plugin.

I attached a new build of Extra Icons: [Extra Icons-2022.1.13.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/10036331/Extra.Icons-2022.1.13.zip). Can you please install it, then go to Extra Icons settings and uncheck "use IDE filename based index" then restart your IDE?

Thx!

![install-from-disk](https://user-images.githubusercontent.com/857535/202578244-06fbc383-2408-4711-bd3b-e2a264a5d968.png)
![how-to-disable-ide-filename-index-usage](https://user-images.githubusercontent.com/857535/202578242-f45cc85f-6131-44c7-8537-5f077562014c.png)

**Comment by jonathanlermitage** [comment]
ho, another question: did you define some custom user icons in Extra Icons?
I recently upgraded a dependency (TwelveMonkeys, used to load some user icons), and some recent builds were affected by bugs leading to high CPU usage. If the new build of Extra Icons doesn't fix the problem, and if you defined some user icons, I will simply revert TwelveMonkeys to an older release.

**Comment by rubensrocha** [comment]
Keeps freezing. I sent the logs to your email, I don't know if it's a problem to post here or not.

I haven't made any changes to the default configuration.

**Comment by jonathanlermitage** [comment]
No problem, this ok, and the log files are very helpful, thx 😎. Logs does not contain sensitive data.  
I am reading the log files and I will let you know if I found something.

**Comment by jonathanlermitage** [comment]
@rubensrocha  
Can you please try this new release: [Extra Icons-2022.1.13.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/10037710/Extra.Icons-2022.1.13.zip)
 Thx!

The logs seem to say there is a problem with a JetBrains API used to detect Angular project. Or, I'm using it the wrong way. 
I detect Angular projects in two ways:  
- by using the IDE filename index, in order to find `angular.json` files
- by using the JetBrains API (`Angular2LangUtil.isAngular2Context(...)`) which detects Angular projects or project modules

I see `Angular2LangUtil.isAngular2Context` in many recent thread-dumps. So, I removed the usage of this API. Angular support will still be good, the IDE filename index should do a good job.  
I hope it will fix high CPU usage 🤞

**Comment by rubensrocha** [comment]
The frequency has decreased, but it continues to happen.

[phpstorm-logs-20221118-09292916377727654903165790.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/10041224/phpstorm-logs-20221118-09292916377727654903165790.zip)

**Comment by jonathanlermitage** [comment]
Can you please try to disable the Angular plugin?  

I looked at the latest thread-dump and there is no reference to Extra Icons.  
I also checked IntelliJ 2022.3 RC's [changelog](https://youtrack.jetbrains.com/articles/IDEA-A-2100661402/IntelliJ-IDEA-2022.3-RC-223.7571.58-build-Release-Notes?utm_source=product&utm_medium=link&utm_campaign=TBA) and I found something interesting: [ Angular: High CPU usage because of inefficient caching of Ivy modules analysis results ](https://youtrack.jetbrains.com/issue/WEB-57461). Unfortunately, PhpStorm 2022.3 is still in Beta and it does not contain this fix yet.  
This is why I think disabling the Angular plugin may help. Just to be sure 😁

**Comment by rubensrocha** [comment]
I've been working on a smaller project and even with all plugins active it worked fine. Now that I'm back to the most complex project I've been working on, both Laravel, the same freezing issue happened again, but it stopped after disabling the Angular plugin.

**Comment by jonathanlermitage** [comment]
Thx! IntelliJ 2022.3 final release has been published recently (with a fix for the Angular plugin which leads to high cpu usage), so PhpStorm 2022.3 should be available in a few days. It _should_ fix the Angular issue. 🤞
