### ISSUE TITLE
[Feature Request] Provide an option to hide blue overlay badges on Clion

### ISSUE THREAD

**Issue by cKaze** [jonathanlermitage/intellij-extra-icons-plugin#139]
## Feature requests

I'm using Extra Icons 2023.2.5-231 on Clion 2023.1.1 in Windows 10.

I found that I got these annoying blue overlay badges on my icons.
![图片](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/83628573/901ca167-fe39-40fb-b47c-9a8f4bac873b)

Even though I know it's an offical feature, it spoils the beauty of the icon, can you provide an option to hide them?

The official description document is as follows:
https://www.jetbrains.com/help/clion/icons-and-symbols.html#prj-view-icons

Thanks for the work.

**Comment by jonathanlermitage** [comment]
Hi, this is weird. Can you please show a full screenshot of the IDE? Also, does it happen on every icon? Thanks.

**Comment by jonathanlermitage** [comment]
Hi! I will see if I can do something. I think I can replace this blue icon by a transparent icon, it could do the trick :D

**Comment by jonathanlermitage** [comment]
I think we can proceed this way. Please note it works only with the old UI for now. There is a [bug](https://youtrack.jetbrains.com/issue/IDEA-321006/cant-override-IDE-SVG-icons-using-IconPathPatcher-in-newUI) with the new UI.  
-> Go to settings, Extra Icons, User Icons tab:  
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/7664b61a-8db2-457b-9009-0f6abb84729e)

Register an icon:
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/c4924e16-ce82-4670-827c-5daf8a4deba4)
Type: IDE  
Icon's name: sourceRootFileLayer.svg
Unzip and pick this custom icon: 
[transparent_badge.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11644743/transparent_badge.zip)
(I wanted to upload the icon directly, but this is an invisible icon, so it's not easy to select&save it 😅)

Validate. Restart your IDE. Now, the badge for souce files should be transparent.  
I picked the icon from there https://jetbrains.design/intellij/resources/icons_list/ (search "sourceRootFileLayer"), and I added "`style="fill-opacity:0"`" to the blue rectangle in order to make it transparent.

**Comment by cKaze** [comment]
Thanks for your reply. This temporary solution works for me!  Now the icon looks much better.
