### ISSUE TITLE
Regex Bug

### ISSUE THREAD

**Issue by franciscomarin98** [jonathanlermitage/intellij-extra-icons-plugin#77]
Hello how things are going I tell you that I am trying to add icons to the jsconfig and tsconfig files but for some strange reason I am not getting the expected result. For this I am using regex.

These are the regex:
```
\.?tsconfig.*\.(js|json)$
\.?jsconfig.*\.(js|json)$
```

![image](https://user-images.githubusercontent.com/50973629/140573305-aed9b713-37b0-4524-9e8a-261ad7bfcb5e.png)
![image](https://user-images.githubusercontent.com/50973629/140573500-ab7bc892-7770-4d26-8bfc-01eb2f008597.png)

I would like you to give me a hand, from my point of view they are fine, but I do not know if something is preventing that

[tsconfig-jsconfig-icons.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/7488703/tsconfig-jsconfig-icons.zip)

**Comment by jonathanlermitage** [comment]
@franciscomarin98 thx for this report. Actually, it's a bit weird: the plugin gets the file name (`.tsconfig.json`), then we can apply a filter on this. But, sometimes, we get a relative path, something like `myproject/.tsconfig.json`.  
As a workaround, you can add a leading `.*/`: 
```
.*/\.?tsconfig.*\.(js|json)$
.*/\.?jsconfig.*\.(js|json)$
```

I will try to fix that, this issue is annoying and totally random :-D
