### ISSUE TITLE
dockerfile icon large in run config

### ISSUE THREAD

**Issue by rala72** [jonathanlermitage/intellij-extra-icons-plugin#94]
## Issues

Please describe the issue:

* the plugin version: 2022.1.2 _(see also in the list below)_
* the OS and IDE version. Open your IDE and go to <kbd>Help</kbd>, <kbd>About</kbd>, then <kbd>Copy</kbd>
> IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022

> Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Non-Bundled Plugins:
    AceJump (3.8.7)
    CMD Support (1.0.5)
    HighlightBracketPair (1.3.4)
    Statistic (4.1.10)
    com.intellij.apacheConfig (221.5080.126)
    com.intellij.ideolog (203.0.28.1)
    com.khmelyuk.multirun (1.13)
    com.nasller.CodeGlancePro (1.3.2)
    com.wakatime.intellij.plugin (13.1.14)
    de.docs_as_co.intellij.plugin.diagramsnet (0.1.12)
    lermitage.intellij.extratci (1.18.0.201)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    org.jetbrains.plugins.go-template (221.5080.126)
    com.github.novotnyr.gitlab-quickmr-idea-plugin (21)
    mobi.hsz.idea.gitignore (4.4.0)
    com.intellij.kubernetes (221.5080.240)
    com.atlassian.bitbucket.references (2022.1.200)
    org.sonarlint.idea (6.7.0.45926)
    String Manipulation (9.4.0)
    MavenRunHelper (4.20.213.3714.1)
    com.intellij.selenium (221.5080.154)
    com.intellij.drools (221.5080.169)
    com.jetbrains.jax.ws (221.5080.169)
    de.platon42.cajon (1.12)
    com.dmarcotte.handlebars (221.5080.240)
    lermitage.intellij.extra.icons (2022.1.2)
    Karma (221.5080.169)
    org.jetbrains.plugins.vue (221.5080.169)
    com.haulmont.jpab (2022.2.2-221)
    com.intellij.bigdatatools (221.4165.63)
    zielu.gittoolbox (212.8.9)
    org.mapstruct.intellij (1.3.1)
    ru.adelf.idea.dotenv (2022.1)
    com.microsoft.tooling.msservices.intellij.azure (3.63.1-2022.1)
    com.intellij.plugins.html.instantEditing (221.5080.169)

Kotlin: 221-1.6.20-release-285-IJ5080.210
* any useful information

The icon is large and every entry below in the dropdown is also now in the same size.
![image](https://user-images.githubusercontent.com/6838669/165901560-9fef2fa6-03db-4471-b681-f52cb1c6a4a6.png)

The usual size:
![image](https://user-images.githubusercontent.com/6838669/165901659-70b99132-6c46-4b4c-bd6d-8a60fd487011.png)

**Comment by jonathanlermitage** [comment]
Hi @rala72 !  
This is fixed, but not yet published. Can you try this release: 
[Extra Icons-2022.1.2.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8590535/Extra.Icons-2022.1.2.zip)? Thx!

I think there's a bug in IntelliJ 2022: SVG icons are rendered correctly in the menus and toolbars, not PNG icons.  
The Docker icon was a PNG file, that's why the icon was too large. I did some rework and now it's a SVG file.
Nota: The `Docker` and `Docker (alternative 2)` are now SVG. The `Docker (alternative 1)` is still a PNG file: I tried to rework it as a SVG file, but I am not a good artist, I think I will simply remove this alt icon 😄
