### ISSUE TITLE
Angular Icons Not Work with Attached Angular Project

### ISSUE THREAD

**Issue by Chris85hh** [jonathanlermitage/intellij-extra-icons-plugin#96]
I am using Rider and have attached an angular project as a folder.
In the angular project the icon works wrong.
angular.json is located in the root of the attached folder
the plugin version: 2022.1.3
![image](https://user-images.githubusercontent.com/27524484/169082690-2de1cfaf-a7b3-43f9-8039-946d5deb8777.png)

a downgrade of plugin version 2022.1.2 works perfectly
![image](https://user-images.githubusercontent.com/27524484/169086877-d11bfc0a-70d5-4903-8a25-805a39111be2.png)

Windows10 Pro 20H2

Build #RD-221.5591.20, built on April 28, 2022
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
.NET Framework 4.0.30319.42000

**Comment by jonathanlermitage** [comment]
I reverted a regression from previous release. 
@Chris85hh can you please try this release? 
[Extra Icons-2022.1.3.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8746048/Extra.Icons-2022.1.3.zip)
Thx!

**Comment by jonathanlermitage** [comment]
Hi @Chris85hh ! Can you please try this new release? Thx! 
[Extra Icons-2022.1.4.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8819342/Extra.Icons-2022.1.4.zip)

This time it looks for `angular.json` files in the root directory and in sub-directories (first level only, it's not recursive for now: I will try to use JetBrains APIs in order to find `angular.json` everywhere by excluding folders marked as _excluded_, like `node_modules`, things like that, otherwise it would ruin performance on big projects).

**Comment by jonathanlermitage** [comment]
Hi @Chris85hh ! Can you please try this new release? Thx! 
[Extra Icons-2022.1.3.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8819358/Extra.Icons-2022.1.3.zip)

This time it looks for `angular.json` files in the root directory and in sub-directories (first level only, it's not recursive for now: I will try to use JetBrains APIs in order to find `angular.json` everywhere by excluding folders marked as _excluded_, like `node_modules`, things like that, otherwise it would ruin performance on big projects).

**Comment by jonathanlermitage** [comment]
Damned, please ignore my comments, the release doesn't work correctly. I will delete my comments later, for now Github seems buggy :-p

**Comment by jonathanlermitage** [comment]
Thx for your test!  
@Chris85hh I tried your sample project (it's very useful, thx!) with Rider and I reproduced the bug. I see that the `Frontend` folder is not part of the project, it's only "attached". The JetBrains API says the project is in `backend\WebApplication1`, and this is why I can't find the `angular.json` file: I search in the _project_ folder only, not in the _attached_ folder. I will try to find a way to detect _attached_ folders.

**Comment by jonathanlermitage** [comment]
@Chris85hh the `indexLayout.xml` file seems interesting. Do you see this file too? `.idea/.idea.WebApplication1/.idea/indexLayout.xml`.  
For me, it contains:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="UserContentModel">
    <attachedFolders>
      <Path>../../../sample-extra-icons-bug-96-angular-support</Path>
      <Path>../../Frontend/testApp</Path>
    </attachedFolders>
    <explicitIncludes />
    <explicitExcludes />
  </component>
</project>
```
I could parse this file in order to detect the project base path.

**Comment by Chris85hh** [comment]
gladly, thanks that you put so much effort into the bug.

yes, i see the file too, with the same content.
but the path to the file is composed of the project name (WebApplication1)

**Comment by jonathanlermitage** [comment]
Finally I found an API that lists all attached folders. @Chris85hh  Can you please try again a new release? 😁 
[Extra Icons-2022.1.3.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/8829580/Extra.Icons-2022.1.3.zip)

It seems to work now: 
![Untitled](https://user-images.githubusercontent.com/857535/171788165-004dfb09-2094-40e4-9b50-3362153a0ef4.png)

**Comment by Chris85hh** [comment]
Thank you, that works well.
